package com.xmedia.springstart.ResponseModel;

import java.io.Serializable;
import com.ligerdev.appbase.utils.db.AntTable;
import com.ligerdev.appbase.utils.db.AntColumn;
import java.util.Date;
/*
	- 30/07/2019 09:06:00: Generated by sql
	select id, employees_id, skills_id, created_date, created_by from skills_employees;
*/
@AntTable(catalog="xtel.management", name="SkillEmployee", label="SkillEmployee", key="id")
public class SkillEmployee implements Serializable, Cloneable {

	private int id;
	private int employeesId;
	private int skillsId;
	private Date createdDate;
	private String createdBy;

	public SkillEmployee(){
	}
	
	public SkillEmployee(int id, int employeesId, int skillsId, Date createdDate, String createdBy){
		this();
		this.id = id;
		this.employeesId = employeesId;
		this.skillsId = skillsId;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}
	
	@AntColumn(name="id", auto_increment=true, size=11, label="id")
	public void setId(int id){
		this.id = id;
	}
	
	@AntColumn(name="id", auto_increment=true, size=11, label="id")
	public int getId(){
		return this.id;
	}
	
	@AntColumn(name="employees_id", size=11, label="employees_id")
	public void setEmployeesId(int employeesId){
		this.employeesId = employeesId;
	}
	
	@AntColumn(name="employees_id", size=11, label="employees_id")
	public int getEmployeesId(){
		return this.employeesId;
	}
	
	@AntColumn(name="skills_id", size=11, label="skills_id")
	public void setSkillsId(int skillsId){
		this.skillsId = skillsId;
	}
	
	@AntColumn(name="skills_id", size=11, label="skills_id")
	public int getSkillsId(){
		return this.skillsId;
	}
	
	@AntColumn(name="created_date", size=19, label="created_date")
	public void setCreatedDate(Date createdDate){
		this.createdDate = createdDate;
	}
	
	@AntColumn(name="created_date", size=19, label="created_date")
	public Date getCreatedDate(){
		return this.createdDate;
	}
	
	@AntColumn(name="created_by", size=45, label="created_by")
	public void setCreatedBy(String createdBy){
		this.createdBy = createdBy;
	}
	
	@AntColumn(name="created_by", size=45, label="created_by")
	public String getCreatedBy(){
		return this.createdBy;
	}
	
	@Override
	public String toString() {
		return "["
			+ "id=" + id
			+ ", employeesId=" + employeesId
			+ ", skillsId=" + skillsId
			+ ", createdDate=" + createdDate
			+ ", createdBy=" + createdBy
			+ "]";
	}
	
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}