package com.xmedia.springstart.data_query_model.Employee;

import java.io.Serializable;

import com.ligerdev.appbase.utils.db.AntTable;
import com.ligerdev.appbase.utils.db.AntColumn;

import java.util.Date;


/*
	- 01/08/2019 10:37:49: Generated by sql
	select distinct e.id as employeeId, e.name as employeeName, e.email as employeeEmail, e.phone as employeePhone, s.name as skillEmployee,
po.name as positionName, pro.name as project, e.start_date as start, e.employee_date as 'to', e.status as statusEmployee from employee e
join skills_employees se on e.id = se.employees_id
join skill s on s.id = se.skills_id 
join employee_position epo on e.id = epo.employee_id
join position po on po.id = epo.position_id 
join project_employee proemp on e.id = proemp.employee_id
join project pro on pro.id = proemp.project_id
;;
*/
@AntTable(catalog = "xtel.management", name = "EmployeeProcessListResponse", label = "EmployeeProcessListResponse", key = "")
public class EmployeeProcessList implements Serializable, Cloneable {

    private int employeeId;
    private String employeeName;
    private String employeeEmail;
    private String employeePhone;
    private String skillEmployee;
    private String positionName;
    private String project;
    private Date start;
    private Date to;
    private String employeeStatus;

    public String getEmployeeStatus() {
        return employeeStatus;
    }

    public void setEmployeeStatus(String employeeStatus) {
        this.employeeStatus = employeeStatus;
    }

    public EmployeeProcessList() {
    }

    public EmployeeProcessList(int employeeId, String employeeName, String employeeEmail, String employeePhone, String skillEmployee, String positionName, String project, Date start, Date to, boolean statusEmployee) {
        this();
        this.employeeId = employeeId;
        this.employeeName = employeeName;
        this.employeeEmail = employeeEmail;
        this.employeePhone = employeePhone;
        this.skillEmployee = skillEmployee;
        this.positionName = positionName;
        this.project = project;
        this.start = start;
        this.to = to;
    }

    @AntColumn(name = "employeeId", size = 11, label = "employeeId")
    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }

    @AntColumn(name = "employeeId", size = 11, label = "employeeId")
    public int getEmployeeId() {
        return this.employeeId;
    }

    @AntColumn(name = "employeeName", size = 45, label = "employeeName")
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    @AntColumn(name = "employeeName", size = 45, label = "employeeName")
    public String getEmployeeName() {
        return this.employeeName;
    }

    @AntColumn(name = "employeeEmail", size = 45, label = "employeeEmail")
    public void setEmployeeEmail(String employeeEmail) {
        this.employeeEmail = employeeEmail;
    }

    @AntColumn(name = "employeeEmail", size = 45, label = "employeeEmail")
    public String getEmployeeEmail() {
        return this.employeeEmail;
    }

    @AntColumn(name = "employeePhone", size = 45, label = "employeePhone")
    public void setEmployeePhone(String employeePhone) {
        this.employeePhone = employeePhone;
    }

    @AntColumn(name = "employeePhone", size = 45, label = "employeePhone")
    public String getEmployeePhone() {
        return this.employeePhone;
    }

    @AntColumn(name = "skillEmployee", size = 45, label = "skillEmployee")
    public void setSkillEmployee(String skillEmployee) {
        this.skillEmployee = skillEmployee;
    }

    @AntColumn(name = "skillEmployee", size = 45, label = "skillEmployee")
    public String getSkillEmployee() {
        return this.skillEmployee;
    }

    @AntColumn(name = "positionName", size = 45, label = "positionName")
    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    @AntColumn(name = "positionName", size = 45, label = "positionName")
    public String getPositionName() {
        return this.positionName;
    }

    @AntColumn(name = "project", size = 45, label = "project")
    public void setProject(String project) {
        this.project = project;
    }

    @AntColumn(name = "project", size = 45, label = "project")
    public String getProject() {
        return this.project;
    }

    @AntColumn(name = "start", size = 19, label = "start")
    public void setStart(Date start) {
        this.start = start;
    }

    @AntColumn(name = "start", size = 19, label = "start")
    public Date getStart() {
        return this.start;
    }

    @AntColumn(name = "to", size = 19, label = "to")
    public void setTo(Date to) {
        this.to = to;
    }

    @AntColumn(name = "to", size = 19, label = "to")
    public Date getTo() {
        return this.to;
    }

    @Override
    public String toString() {
        return "["
                + "employeeId=" + employeeId
                + ", employeeName=" + employeeName
                + ", employeeEmail=" + employeeEmail
                + ", employeePhone=" + employeePhone
                + ", skillEmployee=" + skillEmployee
                + ", positionName=" + positionName
                + ", project=" + project
                + ", start=" + start
                + ", to=" + to
                + "]";
    }

    @Override
    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }
}