package com.xmedia.springstart.data_query_model;

import java.io.Serializable;

import com.ligerdev.appbase.utils.db.AntTable;
import com.ligerdev.appbase.utils.db.AntColumn;

import java.util.Date;


/*
	- 29/07/2019 17:04:18: Generated by sql
	select ee.employee_id as id , e.name as name , e.email as email, s.name as skillName, ex.start as start, ex.now as now FROM employee e join employee_experience ee on e.id = ee.employee_id join experience ex on ex.id = ee.experience_id join skill s on s.id = ee.skills_id
*/
@AntTable(catalog = "xtel.management", name = "SeResponse", label = "SeResponse", key = "id")
public class SeResponse implements Serializable, Cloneable {

    private int id;
    private String name;
    private String email;
    private String skillName;
    private Date start;
    private Date now;

    public SeResponse() {
    }

    public SeResponse(int id, String name, String email, String skillName, Date start, Date now) {
        this();
        this.id = id;
        this.name = name;
        this.email = email;
        this.skillName = skillName;
        this.start = start;
        this.now = now;
    }

    @AntColumn(name = "id", size = 11, label = "id")
    public void setId(int id) {
        this.id = id;
    }

    @AntColumn(name = "id", size = 11, label = "id")
    public int getId() {
        return this.id;
    }

    @AntColumn(name = "name", size = 45, label = "name")
    public void setName(String name) {
        this.name = name;
    }

    @AntColumn(name = "name", size = 45, label = "name")
    public String getName() {
        return this.name;
    }

    @AntColumn(name = "email", size = 45, label = "email")
    public void setEmail(String email) {
        this.email = email;
    }

    @AntColumn(name = "email", size = 45, label = "email")
    public String getEmail() {
        return this.email;
    }

    @AntColumn(name = "skillName", size = 45, label = "skillName")
    public void setSkillName(String skillName) {
        this.skillName = skillName;
    }

    @AntColumn(name = "skillName", size = 45, label = "skillName")
    public String getSkillName() {
        return this.skillName;
    }

    @AntColumn(name = "start", size = 19, label = "start")
    public void setStart(Date start) {
        this.start = start;
    }

    @AntColumn(name = "start", size = 19, label = "start")
    public Date getStart() {
        return this.start;
    }

    @AntColumn(name = "now", size = 19, label = "now")
    public void setNow(Date now) {
        this.now = now;
    }

    @AntColumn(name = "now", size = 19, label = "now")
    public Date getNow() {
        return this.now;
    }

    @Override
    public String toString() {
        return "["
                + "id=" + id
                + ", name=" + name
                + ", email=" + email
                + ", skillName=" + skillName
                + ", start=" + start
                + ", now=" + now
                + "]";
    }

    @Override
    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }
}