package com.xmedia.springstart.data_query_model;

import java.io.Serializable;
import com.ligerdev.appbase.utils.db.AntTable;
import com.ligerdev.appbase.utils.db.AntColumn;
import java.util.Date;


/*
	- 31/07/2019 14:20:17: Generated by sql
	SELECT e.name, e.email, e.status, s.description, se.skill_start, se.skill_end from employee e join skills_employees se on e.id = se.employees_id join skill s on s.id = se.skills_id
*/
@AntTable(catalog = "xtel.management", name = "SkillEmployeeListExperienceModel", label = "SkillEmployeeListExperienceModel", key = "")
public class SkillEmployeeListExperienceModel implements Serializable, Cloneable {

    private String employeeName;
    private String email;
    private String skillName;
    private String description;
    private Date skillStart;
    private Date skillEnd;

    private String status;

    public String getStatus() {
        return status;
    }

    public void setStatus(String wokring) {
        this.status = wokring;
    }

    public SkillEmployeeListExperienceModel() {
    }

    public SkillEmployeeListExperienceModel(String employeeName, String email, String skillName, String description, Date skillStart, Date skillEnd) {
        this();
        this.employeeName = employeeName;
        this.email = email;
        this.skillName = skillName;
        this.description = description;
        this.skillStart = skillStart;
        this.skillEnd = skillEnd;
    }

    @AntColumn(name = "employeeName", size = 45, label = "employeeName")
    public void setEmployeeName(String name) {
        this.employeeName = name;
    }

    @AntColumn(name = "employeeName", size = 45, label = "employeeName")
    public String getEmployeeName() {
        return this.employeeName;
    }

    @AntColumn(name = "email", size = 45, label = "email")
    public void setEmail(String email) {
        this.email = email;
    }

    @AntColumn(name = "email", size = 45, label = "email")
    public String getEmail() {
        return this.email;
    }

    @AntColumn(name = "skillName", size = 4, label = "skillName")
    public void setSkillName(String skillName) {
        this.skillName = skillName;
    }

    @AntColumn(name = "skillName", size = 4, label = "skillName")
    public String getSkillName() {
        return this.skillName;
    }

    @AntColumn(name = "description", size = 45, label = "description")
    public void setDescription(String description) {
        this.description = description;
    }

    @AntColumn(name = "description", size = 45, label = "description")
    public String getDescription() {
        return this.description;
    }

    @AntColumn(name = "skill_start", size = 19, label = "skill_start")
    public void setSkillStart(Date skillStart) {
        this.skillStart = skillStart;
    }

    @AntColumn(name = "skill_start", size = 19, label = "skill_start")
    public Date getSkillStart() {
        return this.skillStart;
    }

    @AntColumn(name = "skill_end", size = 19, label = "skill_end")
    public void setSkillEnd(Date skillEnd) {
        this.skillEnd = skillEnd;
    }

    @AntColumn(name = "skill_end", size = 19, label = "skill_end")
    public Date getSkillEnd() {
        return this.skillEnd;
    }

    @Override
    public String toString() {
        return "["
                + "name=" + employeeName
                + ", email=" + email
                + ", skillName=" + skillName
                + ", description=" + description
                + ", skillStart=" + skillStart
                + ", skillEnd=" + skillEnd
                + "]";
    }

    @Override
    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }
}